2025-05-09 19:38:31,165 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,165 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,170 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,171 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,176 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,176 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,182 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,182 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,189 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,189 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,195 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,196 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,203 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,204 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,225 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,225 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,261 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,262 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,280 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,281 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,298 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,298 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,319 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,320 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,341 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,341 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,370 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,371 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,407 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,407 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,444 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,445 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,479 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,479 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,518 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,518 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,575 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,575 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,634 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,634 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,688 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,688 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,735 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,736 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,793 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,794 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,856 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,857 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,926 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,926 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:31,996 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:31,997 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,075 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,076 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,163 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,163 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,253 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,253 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,336 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,337 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,424 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,425 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,514 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,515 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,603 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,604 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,794 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,795 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:32,898 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:32,899 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,010 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,011 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,133 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,134 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,244 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,244 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,352 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,353 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,468 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,469 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,592 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,592 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,692 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,692 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,808 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,809 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:33,944 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:33,945 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:34,091 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:34,091 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:34,240 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:34,240 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:34,393 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:34,394 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:34,542 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:34,543 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:34,687 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:34,688 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:34,968 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:34,970 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:35,156 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:35,157 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:35,310 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:35,310 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:35,476 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:35,478 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:35,641 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:35,642 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:35,794 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:35,795 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:35,963 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:35,963 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:36,123 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:36,124 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:36,283 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:36,284 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:36,439 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:36,439 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:36,603 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:36,604 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:36,747 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:36,748 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:36,906 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:36,907 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:37,076 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:37,077 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:37,223 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:37,224 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:37,375 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:37,376 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:37,559 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:37,559 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:37,714 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:37,714 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:37,891 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:37,892 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:38,076 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:38,077 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:38,273 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:38,274 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:38,455 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:38,456 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:38,666 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:38,667 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:38,884 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:38,885 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:39,088 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:39,088 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:39,312 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:39,312 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:39,567 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:39,568 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:39,772 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:39,773 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:40,057 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:40,059 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:40,274 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:40,275 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:40,515 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:40,517 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:40,724 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:40,725 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:40,990 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:40,990 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:41,249 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:41,250 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:41,518 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:41,519 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:41,780 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:41,781 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:42,005 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:42,005 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:42,251 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:42,251 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:42,489 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:42,490 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:42,764 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:42,765 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:43,067 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:43,068 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:43,320 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:43,321 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:43,605 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:43,606 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:43,913 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:43,913 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:44,416 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:44,417 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:44,707 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:44,708 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,004 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,005 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,035 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,036 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,044 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,045 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,056 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,056 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,068 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,068 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,077 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,078 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,094 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,094 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,105 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,106 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,116 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,117 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,127 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,127 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,144 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,144 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,159 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,160 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,175 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,175 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,193 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,195 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,211 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,211 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,234 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,235 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,257 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,257 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,285 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,285 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,312 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,316 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,350 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,351 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,384 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,384 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,420 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,421 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,455 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,455 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,488 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,489 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,525 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,527 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,569 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,570 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,619 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,620 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,672 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,672 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,722 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,722 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,778 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,778 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,835 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,836 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,895 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,896 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:45,966 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:45,967 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,021 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,023 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,029 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,030 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,037 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,038 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,042 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,042 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,053 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,054 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,059 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,060 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,068 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,069 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,074 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,074 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,080 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,080 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,086 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,086 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,093 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,093 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,101 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,101 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,111 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,112 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,123 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,123 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,141 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,142 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,155 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,155 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,170 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,171 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,184 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,185 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,201 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,201 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,219 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,219 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,240 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,240 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,255 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,255 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,279 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,280 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,298 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,299 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,320 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,321 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,340 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,341 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,361 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,361 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,380 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,380 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,402 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,403 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,429 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,429 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,461 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,462 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,490 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,490 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,515 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,516 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,543 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,544 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,569 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,570 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,598 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,599 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,635 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,636 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,669 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,669 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,705 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,706 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,750 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,751 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,796 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,797 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,840 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,841 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,891 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,891 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:49,946 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:49,946 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,001 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,002 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,060 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,060 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,121 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,122 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,184 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,185 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,235 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,235 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,299 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,300 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,361 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,361 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,425 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,426 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,490 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,490 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,561 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,561 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,626 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,627 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,702 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,703 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,768 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,768 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,842 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,842 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:50,921 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:50,921 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,000 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,001 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,085 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,086 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,176 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,176 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,283 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,284 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,384 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,384 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,488 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,489 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,589 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,589 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,684 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,684 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,802 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,802 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:51,922 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:51,922 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,053 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,054 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,174 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,174 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,295 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,296 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,406 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,406 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,544 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,544 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,686 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,686 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,822 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,823 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:52,952 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:52,953 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:53,083 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:53,084 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:53,250 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:53,251 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:53,400 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:53,400 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:53,563 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:53,564 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:53,716 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:53,717 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:53,860 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:53,861 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,012 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,013 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,171 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,172 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,321 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,322 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,475 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,475 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,619 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,619 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,784 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,784 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:54,938 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:54,939 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:55,095 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:55,095 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:55,270 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:55,271 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:55,440 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:55,440 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:55,617 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:55,617 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:55,792 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:55,792 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:55,960 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:55,961 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:56,136 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:56,137 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:56,291 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:56,292 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:56,443 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:56,444 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:56,630 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:56,631 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:57,146 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:57,146 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:57,333 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:57,334 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:57,520 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:57,522 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:57,695 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:57,696 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:57,878 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:57,878 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:58,057 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:58,057 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

2025-05-09 19:38:58,224 - ERROR - 미디어 정보 저장 중 오류 발생: table media_files has no column named created_at
2025-05-09 19:38:58,226 - ERROR - Traceback (most recent call last):
  File "/Volumes/p31/coding/indexer_quick/app/database/media/insert.py", line 48, in insert_media
    cursor.execute('''
sqlite3.OperationalError: table media_files has no column named created_at

